### ISSUE TITLE
CUDA Runtime Error: the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by Superbia-zyb** [ximinng/VectorFusion-pytorch#3]
Hi! Thanks for your open-source project.
I try to run your code on GPU and meet a problem caused by diffvg: "CUDA Runtime Error: the provided PTX was compiled with an unsupported toolchain." Which correct version of CUDA should I use?  I use "V11.8.89" now.

**Comment by Superbia-zyb** [comment]
I hope can get come advice from you.

**Comment by ximinng** [comment]
hi, Superbia-zyb,

First check your CUDA version:
```
nvcc -V
```
If the CUDA version is higher than 11.6, that's fine, otherwise you'll need to find a matching version in pytorch yourself.

have a nice day~
